networks:
  remoteproxy:
    external: true

services:

  stockfinder_images:
    image: flashspys/nginx-static
    container_name: stockfinder_images
    ports:
      # - 200.20.0.1:4444:80
      - 0.0.0.0:4444:80
    networks:
      remoteproxy:
        ipv4_address: '200.20.0.221'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 256M
        reservations:
          cpus: '1'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 600s
    # labels:
    #   traefik.enable: true
    #   traefik.http.routers.stockfinder_images.rule: Host(`images.stockfinder.tech`)
    #   traefik.http.routers.stockfinder_images.entrypoints: http-ext
    #   traefik.http.middlewares.stockfinder_images-https-redirect.redirectscheme.scheme: https-ext
    #   traefik.http.routers.stockfinder_images.middlewares: stockfinder_images-https-redirect
    #   traefik.http.routers.stockfinder_images-secure.entrypoints: https-ext
    #   traefik.http.routers.stockfinder_images-secure.rule: Host(`images.stockfinder.tech`)
    #   traefik.http.routers.stockfinder_images-secure.tls: true
    #   traefik.http.routers.stockfinder_images-secure.service: stockfinder_images
    #   traefik.http.services.stockfinder_images.loadbalancer.server.port: 80
    volumes:
      - ./nginx/static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/robots.txt:/files/robots.txt