networks:
  caddy_external_net:
    external: true

services:

  stockfinder_images:
    image: flashspys/nginx-static
    container_name: stockfinder_images
    ports:
      - 4444:80
    networks:
      - caddy_external_net
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 256M
        reservations:
          cpus: '1'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 600s
    labels:
      caddy: images.gpufinder.ovh
      caddy.route.reverse_proxy: "{{upstreams 80}}"

    volumes:
      - ./nginx/static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/robots.txt:/files/robots.txt